### ISSUE TITLE
address already in use

### ISSUE THREAD

**Issue by city-invoker** [trpc-ecosystem/go-gateway#6]
* get_listener_err||fasthttp reuseport listen err||type:business, code:999, msg:address already in use, caused by address already in use

i try make run and got this, i use another port and the problem remain

**Comment by Quons** [comment]
Please provide more information, just like the error message said: 'port is in use.' Is it okay to run https://github.com/trpc-ecosystem/go-gateway/tree/main/example/loader/file on a local machine?
